# Generated by Django 4.2.11 on 2024-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'General')], default=0),
        ),
    ]
