# Generated by Django 4.2.11 on 2024-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_subscription_id',
            field=models.CharField(default=122, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
    ]
