# Generated by Django 4.2.11 on 2024-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'cancelled')], default=0),
        ),
    ]
