# Generated by Django 4.2.11 on 2024-06-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
