# Generated by Django 4.2.11 on 2024-06-22 06:44

from django.db import migrations
import utils.constraint_fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=utils.constraint_fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='dp/'),
        ),
    ]
